
# update preprints:

- id: doi:10.1101/2024.10.11.617967
  type: preprint
  publisher: bioRxiv
  date: '2024-10-11'
  tags:
    - human diversity
    - metascience

- id: doi:10.1101/2021.01.07.425684
  type: preprint
  publisher: bioRxiv
  tags:
    - Indonesia

- id: doi:10.1101/2022.04.24.489025 
  type: preprint
  publisher: bioRxiv
  date: '2024-5-06'
  tags:
    - Indonesia
    - microbiome

- id: doi:10.1101/466631
  type: preprint
  publisher: bioRxiv
  tags:
    - chimpanzees
    - iPSCs

# remove duplicates:

- id: doi:10.1016/j.ajhg.2012.01.001
  remove: true

- id: doi:10.1101/2023.02.13.528361
  remove: true

- id: doi:10.1101/2024.05.07.593052
  remove: true

- id: doi:10.7554/eLife.103592
  remove: true

- id: doi:10.1101/2024.04.11.24305690 
  remove: true

- id: doi:10.1101/2023.11.16.567318
  remove: true

- id: doi:10.1101/2021.06.27.450107
  remove: true

- id: doi:10.1101/2020.07.09.196444
  remove: true

- id: doi:10.1101/2020.09.25.313726
  remove: true  

- id: doi:10.1101/002261
  remove: true

- id: doi:10.1101/008862
  remove: true


# tags etc:

- id: doi:10.1016/j.ajhg.2023.10.012
  tags:
    - perspective
    - human diversity

- id: 10.7554/eLife.103592.1
  publisher: eLife
  tags:
    - marsupials

- id: doi:10.1126/science.adh0745
  tags:
    - perspective

- id: doi:10.1186/s13059-023-02856-6
  tags:
    - review
    - MAVE

- id: doi:10.1111/febs.15885
  tags:
    - review
    - human evolution
    - iPSCs

- id: doi:10.1038/s41576-022-00469-6
  tags:
    - perspective

- id: doi:10.1093/molbev/msab238
  tags:
    - Papua New Guinea
    - human evolution

- id: doi:10.1371/journal.pgen.1008749
  tags:
    - Indonesia
    - human diversity
    - gene regulation

- id: doi:10.1093/molbev/msz037
  tags:
    - human evolution

- id: doi:10.1101/013888
  tags: 
    - iPSCs
    - gene regulation

- id: doi:10.1038/nature18964
  tags:
    - human diversity

- id: doi:10.1126/science.aab3761
  tags:
    - human diversity

- id: doi:10.7554/eLife.07103
  tags:
    - chimpanzee
    - iPSCs
    - resource

- id: doi:10.1371/journal.pone.0118307
  tags:
    - iPSCs

- id: doi:10.1038/nature13673
  tags:
    - human evolution
  
- id: doi:10.1371/journal.pone.0098076
  tags:
    - human evolution

- id: doi:10.1186/1741-7007-12-42
  tags:
    - gene expression
    - methods

- id: doi:10.1371/journal.pgen.1003912
  tags:
    - human diversity

- id: doi:10.1186/1471-2156-14-87
  tags:
    - methods

- id: doi:10.1111/ahg.12028
  tags:
    - human diversity
    - India

- id: doi:10.3378/027.085.0313
  tags:
    - human evolution
    - human diversity

- id: doi:10.1038/nrg3229
  tags:
    - review
    - gene regulation

- id: doi:10.1016/j.ajhg.2012.05.015
  tags:
    - human diversity

- id: doi:10.1007/s00439-011-1111-9
  tags:
    - methods

- id: doi:10.1126/science.1215040
  tags:
    - human diversity

- id: doi:10.1016/j.ajhg.2011.11.010
  tags: 
    - human evolution
    - India
    - human diversity

- id: doi:10.1093/molbev/msr190
  tags:
    - human evolution
    - India
    - lactase persistence

- id: doi:10.1126/science.1211177
  tags:
    - human diversity
    - human evolution

- id: doi:10.1093/molbev/msq288
  tags:
    - human diversity
    - India

- id: doi:10.1038/ejhg.2009.168
  tags:
    - human diversity
    - India

- id: doi:10.1038/hdy.2008.89
  tags: 
    - human diversity
    - human evolution
   
- id: doi:10.1007/s00439-007-0432-1
  tags:
    - CFTR
    - Hutterites

- id: doi:10.1101/gr.224436.117
  tags: 
    - gene regulation
    - iPSCs

- id: doi:10.1371/journal.pgen.1010470
  tags: 
    - denisovan introgression
    - human diversity

- id: doi:10.1016/j.ajhg.2021.11.017
  tags:
    - Indonesia
    - human diversity
    - gene regulation

- id: doi:10.1186/s13059-023-02856-6
  tags:
    - MAVE
    - human evolution

- id: doi:10.46471/gigabyte.118 
  tags: 
    - marsupials
    - resource
